# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   message(FATAL_ERROR "CMake >= 2.6.0 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.6)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_targetsDefined)
set(_targetsNotDefined)
set(_expectedTargets)
foreach(_expectedTarget Qhull::qhullcpp Qhull::qhullstatic Qhull::qhullstatic_r Qhull::qhull_r Qhull::qhull Qhull::rbox Qhull::qconvex Qhull::qdelaunay Qhull::qvoronoi Qhull::qhalf Qhull::libqhull Qhull::qhull_p)
  list(APPEND _expectedTargets ${_expectedTarget})
  if(NOT TARGET ${_expectedTarget})
    list(APPEND _targetsNotDefined ${_expectedTarget})
  endif()
  if(TARGET ${_expectedTarget})
    list(APPEND _targetsDefined ${_expectedTarget})
  endif()
endforeach()
if("${_targetsDefined}" STREQUAL "${_expectedTargets}")
  unset(_targetsDefined)
  unset(_targetsNotDefined)
  unset(_expectedTargets)
  set(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT "${_targetsDefined}" STREQUAL "")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_targetsDefined}\nTargets not yet defined: ${_targetsNotDefined}\n")
endif()
unset(_targetsDefined)
unset(_targetsNotDefined)
unset(_expectedTargets)


# Create imported target Qhull::qhullcpp
add_library(Qhull::qhullcpp STATIC IMPORTED)

# Create imported target Qhull::qhullstatic
add_library(Qhull::qhullstatic STATIC IMPORTED)

# Create imported target Qhull::qhullstatic_r
add_library(Qhull::qhullstatic_r STATIC IMPORTED)

# Create imported target Qhull::qhull_r
add_library(Qhull::qhull_r SHARED IMPORTED)

# Create imported target Qhull::qhull
add_executable(Qhull::qhull IMPORTED)

# Create imported target Qhull::rbox
add_executable(Qhull::rbox IMPORTED)

# Create imported target Qhull::qconvex
add_executable(Qhull::qconvex IMPORTED)

# Create imported target Qhull::qdelaunay
add_executable(Qhull::qdelaunay IMPORTED)

# Create imported target Qhull::qvoronoi
add_executable(Qhull::qvoronoi IMPORTED)

# Create imported target Qhull::qhalf
add_executable(Qhull::qhalf IMPORTED)

# Create imported target Qhull::libqhull
add_library(Qhull::libqhull SHARED IMPORTED)

# Create imported target Qhull::qhull_p
add_library(Qhull::qhull_p SHARED IMPORTED)

# Import target "Qhull::qhullcpp" for configuration "Debug"
set_property(TARGET Qhull::qhullcpp APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(Qhull::qhullcpp PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LOCATION_DEBUG "C:/Development/op3d_active/qhull-7.3.1/msvc/Debug/qhullcpp.lib"
  )

# Import target "Qhull::qhullstatic" for configuration "Debug"
set_property(TARGET Qhull::qhullstatic APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(Qhull::qhullstatic PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "C"
  IMPORTED_LOCATION_DEBUG "C:/Development/op3d_active/qhull-7.3.1/msvc/Debug/qhullstatic.lib"
  )

# Import target "Qhull::qhullstatic_r" for configuration "Debug"
set_property(TARGET Qhull::qhullstatic_r APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(Qhull::qhullstatic_r PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "C"
  IMPORTED_LOCATION_DEBUG "C:/Development/op3d_active/qhull-7.3.1/msvc/Debug/qhullstatic_r.lib"
  )

# Import target "Qhull::qhull_r" for configuration "Debug"
set_property(TARGET Qhull::qhull_r APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(Qhull::qhull_r PROPERTIES
  IMPORTED_IMPLIB_DEBUG "C:/Development/op3d_active/qhull-7.3.1/msvc/Debug/qhull_r.lib"
  IMPORTED_LOCATION_DEBUG "C:/Development/op3d_active/qhull-7.3.1/msvc/Debug/qhull_r.dll"
  )

# Import target "Qhull::qhull" for configuration "Debug"
set_property(TARGET Qhull::qhull APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(Qhull::qhull PROPERTIES
  IMPORTED_LOCATION_DEBUG "C:/Development/op3d_active/qhull-7.3.1/msvc/Debug/qhull.exe"
  )

# Import target "Qhull::rbox" for configuration "Debug"
set_property(TARGET Qhull::rbox APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(Qhull::rbox PROPERTIES
  IMPORTED_LOCATION_DEBUG "C:/Development/op3d_active/qhull-7.3.1/msvc/Debug/rbox.exe"
  )

# Import target "Qhull::qconvex" for configuration "Debug"
set_property(TARGET Qhull::qconvex APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(Qhull::qconvex PROPERTIES
  IMPORTED_LOCATION_DEBUG "C:/Development/op3d_active/qhull-7.3.1/msvc/Debug/qconvex.exe"
  )

# Import target "Qhull::qdelaunay" for configuration "Debug"
set_property(TARGET Qhull::qdelaunay APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(Qhull::qdelaunay PROPERTIES
  IMPORTED_LOCATION_DEBUG "C:/Development/op3d_active/qhull-7.3.1/msvc/Debug/qdelaunay.exe"
  )

# Import target "Qhull::qvoronoi" for configuration "Debug"
set_property(TARGET Qhull::qvoronoi APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(Qhull::qvoronoi PROPERTIES
  IMPORTED_LOCATION_DEBUG "C:/Development/op3d_active/qhull-7.3.1/msvc/Debug/qvoronoi.exe"
  )

# Import target "Qhull::qhalf" for configuration "Debug"
set_property(TARGET Qhull::qhalf APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(Qhull::qhalf PROPERTIES
  IMPORTED_LOCATION_DEBUG "C:/Development/op3d_active/qhull-7.3.1/msvc/Debug/qhalf.exe"
  )

# Import target "Qhull::libqhull" for configuration "Debug"
set_property(TARGET Qhull::libqhull APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(Qhull::libqhull PROPERTIES
  IMPORTED_IMPLIB_DEBUG "C:/Development/op3d_active/qhull-7.3.1/msvc/Debug/qhull.lib"
  IMPORTED_LOCATION_DEBUG "C:/Development/op3d_active/qhull-7.3.1/msvc/Debug/qhull.dll"
  )

# Import target "Qhull::qhull_p" for configuration "Debug"
set_property(TARGET Qhull::qhull_p APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(Qhull::qhull_p PROPERTIES
  IMPORTED_IMPLIB_DEBUG "C:/Development/op3d_active/qhull-7.3.1/msvc/Debug/qhull_p.lib"
  IMPORTED_LOCATION_DEBUG "C:/Development/op3d_active/qhull-7.3.1/msvc/Debug/qhull_p.dll"
  )

# Import target "Qhull::qhullcpp" for configuration "Release"
set_property(TARGET Qhull::qhullcpp APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(Qhull::qhullcpp PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE "C:/Development/op3d_active/qhull-7.3.1/msvc/Release/qhullcpp.lib"
  )

# Import target "Qhull::qhullstatic" for configuration "Release"
set_property(TARGET Qhull::qhullstatic APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(Qhull::qhullstatic PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "C"
  IMPORTED_LOCATION_RELEASE "C:/Development/op3d_active/qhull-7.3.1/msvc/Release/qhullstatic.lib"
  )

# Import target "Qhull::qhullstatic_r" for configuration "Release"
set_property(TARGET Qhull::qhullstatic_r APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(Qhull::qhullstatic_r PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "C"
  IMPORTED_LOCATION_RELEASE "C:/Development/op3d_active/qhull-7.3.1/msvc/Release/qhullstatic_r.lib"
  )

# Import target "Qhull::qhull_r" for configuration "Release"
set_property(TARGET Qhull::qhull_r APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(Qhull::qhull_r PROPERTIES
  IMPORTED_IMPLIB_RELEASE "C:/Development/op3d_active/qhull-7.3.1/msvc/Release/qhull_r.lib"
  IMPORTED_LOCATION_RELEASE "C:/Development/op3d_active/qhull-7.3.1/msvc/Release/qhull_r.dll"
  )

# Import target "Qhull::qhull" for configuration "Release"
set_property(TARGET Qhull::qhull APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(Qhull::qhull PROPERTIES
  IMPORTED_LOCATION_RELEASE "C:/Development/op3d_active/qhull-7.3.1/msvc/Release/qhull.exe"
  )

# Import target "Qhull::rbox" for configuration "Release"
set_property(TARGET Qhull::rbox APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(Qhull::rbox PROPERTIES
  IMPORTED_LOCATION_RELEASE "C:/Development/op3d_active/qhull-7.3.1/msvc/Release/rbox.exe"
  )

# Import target "Qhull::qconvex" for configuration "Release"
set_property(TARGET Qhull::qconvex APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(Qhull::qconvex PROPERTIES
  IMPORTED_LOCATION_RELEASE "C:/Development/op3d_active/qhull-7.3.1/msvc/Release/qconvex.exe"
  )

# Import target "Qhull::qdelaunay" for configuration "Release"
set_property(TARGET Qhull::qdelaunay APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(Qhull::qdelaunay PROPERTIES
  IMPORTED_LOCATION_RELEASE "C:/Development/op3d_active/qhull-7.3.1/msvc/Release/qdelaunay.exe"
  )

# Import target "Qhull::qvoronoi" for configuration "Release"
set_property(TARGET Qhull::qvoronoi APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(Qhull::qvoronoi PROPERTIES
  IMPORTED_LOCATION_RELEASE "C:/Development/op3d_active/qhull-7.3.1/msvc/Release/qvoronoi.exe"
  )

# Import target "Qhull::qhalf" for configuration "Release"
set_property(TARGET Qhull::qhalf APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(Qhull::qhalf PROPERTIES
  IMPORTED_LOCATION_RELEASE "C:/Development/op3d_active/qhull-7.3.1/msvc/Release/qhalf.exe"
  )

# Import target "Qhull::libqhull" for configuration "Release"
set_property(TARGET Qhull::libqhull APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(Qhull::libqhull PROPERTIES
  IMPORTED_IMPLIB_RELEASE "C:/Development/op3d_active/qhull-7.3.1/msvc/Release/qhull.lib"
  IMPORTED_LOCATION_RELEASE "C:/Development/op3d_active/qhull-7.3.1/msvc/Release/qhull.dll"
  )

# Import target "Qhull::qhull_p" for configuration "Release"
set_property(TARGET Qhull::qhull_p APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(Qhull::qhull_p PROPERTIES
  IMPORTED_IMPLIB_RELEASE "C:/Development/op3d_active/qhull-7.3.1/msvc/Release/qhull_p.lib"
  IMPORTED_LOCATION_RELEASE "C:/Development/op3d_active/qhull-7.3.1/msvc/Release/qhull_p.dll"
  )

# Import target "Qhull::qhullcpp" for configuration "MinSizeRel"
set_property(TARGET Qhull::qhullcpp APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(Qhull::qhullcpp PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_MINSIZEREL "CXX"
  IMPORTED_LOCATION_MINSIZEREL "C:/Development/op3d_active/qhull-7.3.1/msvc/MinSizeRel/qhullcpp.lib"
  )

# Import target "Qhull::qhullstatic" for configuration "MinSizeRel"
set_property(TARGET Qhull::qhullstatic APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(Qhull::qhullstatic PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_MINSIZEREL "C"
  IMPORTED_LOCATION_MINSIZEREL "C:/Development/op3d_active/qhull-7.3.1/msvc/MinSizeRel/qhullstatic.lib"
  )

# Import target "Qhull::qhullstatic_r" for configuration "MinSizeRel"
set_property(TARGET Qhull::qhullstatic_r APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(Qhull::qhullstatic_r PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_MINSIZEREL "C"
  IMPORTED_LOCATION_MINSIZEREL "C:/Development/op3d_active/qhull-7.3.1/msvc/MinSizeRel/qhullstatic_r.lib"
  )

# Import target "Qhull::qhull_r" for configuration "MinSizeRel"
set_property(TARGET Qhull::qhull_r APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(Qhull::qhull_r PROPERTIES
  IMPORTED_IMPLIB_MINSIZEREL "C:/Development/op3d_active/qhull-7.3.1/msvc/MinSizeRel/qhull_r.lib"
  IMPORTED_LOCATION_MINSIZEREL "C:/Development/op3d_active/qhull-7.3.1/msvc/MinSizeRel/qhull_r.dll"
  )

# Import target "Qhull::qhull" for configuration "MinSizeRel"
set_property(TARGET Qhull::qhull APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(Qhull::qhull PROPERTIES
  IMPORTED_LOCATION_MINSIZEREL "C:/Development/op3d_active/qhull-7.3.1/msvc/MinSizeRel/qhull.exe"
  )

# Import target "Qhull::rbox" for configuration "MinSizeRel"
set_property(TARGET Qhull::rbox APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(Qhull::rbox PROPERTIES
  IMPORTED_LOCATION_MINSIZEREL "C:/Development/op3d_active/qhull-7.3.1/msvc/MinSizeRel/rbox.exe"
  )

# Import target "Qhull::qconvex" for configuration "MinSizeRel"
set_property(TARGET Qhull::qconvex APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(Qhull::qconvex PROPERTIES
  IMPORTED_LOCATION_MINSIZEREL "C:/Development/op3d_active/qhull-7.3.1/msvc/MinSizeRel/qconvex.exe"
  )

# Import target "Qhull::qdelaunay" for configuration "MinSizeRel"
set_property(TARGET Qhull::qdelaunay APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(Qhull::qdelaunay PROPERTIES
  IMPORTED_LOCATION_MINSIZEREL "C:/Development/op3d_active/qhull-7.3.1/msvc/MinSizeRel/qdelaunay.exe"
  )

# Import target "Qhull::qvoronoi" for configuration "MinSizeRel"
set_property(TARGET Qhull::qvoronoi APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(Qhull::qvoronoi PROPERTIES
  IMPORTED_LOCATION_MINSIZEREL "C:/Development/op3d_active/qhull-7.3.1/msvc/MinSizeRel/qvoronoi.exe"
  )

# Import target "Qhull::qhalf" for configuration "MinSizeRel"
set_property(TARGET Qhull::qhalf APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(Qhull::qhalf PROPERTIES
  IMPORTED_LOCATION_MINSIZEREL "C:/Development/op3d_active/qhull-7.3.1/msvc/MinSizeRel/qhalf.exe"
  )

# Import target "Qhull::libqhull" for configuration "MinSizeRel"
set_property(TARGET Qhull::libqhull APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(Qhull::libqhull PROPERTIES
  IMPORTED_IMPLIB_MINSIZEREL "C:/Development/op3d_active/qhull-7.3.1/msvc/MinSizeRel/qhull.lib"
  IMPORTED_LOCATION_MINSIZEREL "C:/Development/op3d_active/qhull-7.3.1/msvc/MinSizeRel/qhull.dll"
  )

# Import target "Qhull::qhull_p" for configuration "MinSizeRel"
set_property(TARGET Qhull::qhull_p APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(Qhull::qhull_p PROPERTIES
  IMPORTED_IMPLIB_MINSIZEREL "C:/Development/op3d_active/qhull-7.3.1/msvc/MinSizeRel/qhull_p.lib"
  IMPORTED_LOCATION_MINSIZEREL "C:/Development/op3d_active/qhull-7.3.1/msvc/MinSizeRel/qhull_p.dll"
  )

# Import target "Qhull::qhullcpp" for configuration "RelWithDebInfo"
set_property(TARGET Qhull::qhullcpp APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(Qhull::qhullcpp PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "CXX"
  IMPORTED_LOCATION_RELWITHDEBINFO "C:/Development/op3d_active/qhull-7.3.1/msvc/RelWithDebInfo/qhullcpp.lib"
  )

# Import target "Qhull::qhullstatic" for configuration "RelWithDebInfo"
set_property(TARGET Qhull::qhullstatic APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(Qhull::qhullstatic PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "C"
  IMPORTED_LOCATION_RELWITHDEBINFO "C:/Development/op3d_active/qhull-7.3.1/msvc/RelWithDebInfo/qhullstatic.lib"
  )

# Import target "Qhull::qhullstatic_r" for configuration "RelWithDebInfo"
set_property(TARGET Qhull::qhullstatic_r APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(Qhull::qhullstatic_r PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "C"
  IMPORTED_LOCATION_RELWITHDEBINFO "C:/Development/op3d_active/qhull-7.3.1/msvc/RelWithDebInfo/qhullstatic_r.lib"
  )

# Import target "Qhull::qhull_r" for configuration "RelWithDebInfo"
set_property(TARGET Qhull::qhull_r APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(Qhull::qhull_r PROPERTIES
  IMPORTED_IMPLIB_RELWITHDEBINFO "C:/Development/op3d_active/qhull-7.3.1/msvc/RelWithDebInfo/qhull_r.lib"
  IMPORTED_LOCATION_RELWITHDEBINFO "C:/Development/op3d_active/qhull-7.3.1/msvc/RelWithDebInfo/qhull_r.dll"
  )

# Import target "Qhull::qhull" for configuration "RelWithDebInfo"
set_property(TARGET Qhull::qhull APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(Qhull::qhull PROPERTIES
  IMPORTED_LOCATION_RELWITHDEBINFO "C:/Development/op3d_active/qhull-7.3.1/msvc/RelWithDebInfo/qhull.exe"
  )

# Import target "Qhull::rbox" for configuration "RelWithDebInfo"
set_property(TARGET Qhull::rbox APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(Qhull::rbox PROPERTIES
  IMPORTED_LOCATION_RELWITHDEBINFO "C:/Development/op3d_active/qhull-7.3.1/msvc/RelWithDebInfo/rbox.exe"
  )

# Import target "Qhull::qconvex" for configuration "RelWithDebInfo"
set_property(TARGET Qhull::qconvex APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(Qhull::qconvex PROPERTIES
  IMPORTED_LOCATION_RELWITHDEBINFO "C:/Development/op3d_active/qhull-7.3.1/msvc/RelWithDebInfo/qconvex.exe"
  )

# Import target "Qhull::qdelaunay" for configuration "RelWithDebInfo"
set_property(TARGET Qhull::qdelaunay APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(Qhull::qdelaunay PROPERTIES
  IMPORTED_LOCATION_RELWITHDEBINFO "C:/Development/op3d_active/qhull-7.3.1/msvc/RelWithDebInfo/qdelaunay.exe"
  )

# Import target "Qhull::qvoronoi" for configuration "RelWithDebInfo"
set_property(TARGET Qhull::qvoronoi APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(Qhull::qvoronoi PROPERTIES
  IMPORTED_LOCATION_RELWITHDEBINFO "C:/Development/op3d_active/qhull-7.3.1/msvc/RelWithDebInfo/qvoronoi.exe"
  )

# Import target "Qhull::qhalf" for configuration "RelWithDebInfo"
set_property(TARGET Qhull::qhalf APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(Qhull::qhalf PROPERTIES
  IMPORTED_LOCATION_RELWITHDEBINFO "C:/Development/op3d_active/qhull-7.3.1/msvc/RelWithDebInfo/qhalf.exe"
  )

# Import target "Qhull::libqhull" for configuration "RelWithDebInfo"
set_property(TARGET Qhull::libqhull APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(Qhull::libqhull PROPERTIES
  IMPORTED_IMPLIB_RELWITHDEBINFO "C:/Development/op3d_active/qhull-7.3.1/msvc/RelWithDebInfo/qhull.lib"
  IMPORTED_LOCATION_RELWITHDEBINFO "C:/Development/op3d_active/qhull-7.3.1/msvc/RelWithDebInfo/qhull.dll"
  )

# Import target "Qhull::qhull_p" for configuration "RelWithDebInfo"
set_property(TARGET Qhull::qhull_p APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(Qhull::qhull_p PROPERTIES
  IMPORTED_IMPLIB_RELWITHDEBINFO "C:/Development/op3d_active/qhull-7.3.1/msvc/RelWithDebInfo/qhull_p.lib"
  IMPORTED_LOCATION_RELWITHDEBINFO "C:/Development/op3d_active/qhull-7.3.1/msvc/RelWithDebInfo/qhull_p.dll"
  )

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
